# Run `pre-commit autoupdate` to update to the latest pre-commit hooks version.
minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: &whitespace_excludes |
          (?x)^(
            .*\.(md|rst|map|bin)$|
            components/debug_probe/DAP/.*|
          )$
      - id: end-of-file-fixer
        exclude: *whitespace_excludes
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer
  - repo: https://github.com/espressif/astyle_py.git
    rev: v1.1.0
    hooks:
      - id: astyle_py
        args: ['--astyle-version=3.4.7', '--rules=astyle-rules.yml']
  - repo: https://github.com/espressif/check-copyright/
    rev: v1.1.1
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter                # Lints commit messages for conventional format
        stages: [commit-msg]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell                                    # Code spell checker
        args: ["--write-changes"]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [--number] # Keep numbering for ordered lists
        additional_dependencies:
          - mdformat-gfm # Support for GitHub Flavored Markdown (GFM), including tables, task lists, strikethroughs, and autolinks.
          - mdformat-ruff # Formats Python code blocks in Markdown files according to the `ruff` linter's style.
          - mdformat-simple-breaks # Ensures that single line breaks in Markdown are converted to `<br>` t
